server:
  port: 8090
# 分组任务配置
chatbot-api:
  launchList: group01,group02 # 启动几组，就配置几组
  group01:
    groupName: 组1
    groupId: 28885518425541 # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey: aikey
    cronExpression: 0/30 * * * * ?
    silenced: false
  group02:
    groupName: 组2
    groupId: 28885518425541 # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey: aikey
    cronExpression: 0/30 * * * * ?
    silenced: true